# Generated by Django 5.2.4 on 2025-08-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destination',
            name='activity',
        ),
        migrations.AddField(
            model_name='destination',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
