# Generated by Django 5.2.4 on 2025-08-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0002_remove_destination_activity_destination_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
