# Generated by Django 5.2.4 on 2025-08-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trip', '0005_hotel_destination_hotel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
    ]
